- name: Debug remote_mode variable
  debug:
    msg:
      - "remote_mode is set to: {{ remote_mode }}"
      - "remote_mode as bool: {{ remote_mode | bool }}"
      - "ansible_env.HOME: {{ ansible_env.HOME }}"
      - "playbook_dir: {{ playbook_dir }}"
  tags: templar

- name: Set templar_path based on deployment mode
  set_fact:
    templar_path: "{{ ansible_env.HOME }}/templar"
  when: remote_mode is defined and remote_mode | bool
  tags: templar

- name: Set templar_path for local deployment
  set_fact:
    templar_path: "{{ playbook_dir }}/../.."
  when: remote_mode is not defined or not remote_mode | bool
  tags: templar

- name: Debug templar_path after setting
  debug:
    msg: "templar_path is set to: {{ templar_path }}"
  tags: templar

- name: Include local deployment tasks
  include_tasks: local.yml
  when: not (remote_mode | default(false) | bool)
  tags: templar

- name: Include remote deployment tasks
  include_tasks: remote.yml
  when: remote_mode | default(false) | bool
  tags: templar

- name: Check available GPU count (informational only)
  shell: nvidia-smi --list-gpu | wc -l
  register: gpu_count
  changed_when: false
  failed_when: false
  tags: templar

- name: Report available GPUs (informational only)
  debug:
    msg: "Found {{ gpu_count.stdout|int if gpu_count.stdout is defined else 0 }} GPU(s)"
  tags: templar

- name: Check if Python venv exists
  stat:
    path: "{{ templar_path }}/.venv"
  register: venv_exists
  tags: templar

- name: Create Python virtual environment with uv
  shell: uv venv
  args:
    chdir: "{{ templar_path }}"
  when: not venv_exists.stat.exists
  tags: templar

- name: Install dependencies with uv sync
  shell: |
    source .venv/bin/activate
    uv sync
  args:
    chdir: "{{ templar_path }}"
    executable: /bin/bash
  tags: templar

- name: Install Node dotenv package in templar dir
  shell: npm install dotenv
  args:
    chdir: "{{ templar_path }}"
  tags: templar

- name: Ensure .env file has proper permissions
  file:
    path: "{{ templar_path }}/.env"
    mode: "0644"
  tags: templar

- name: Configure .env for templar
  template:
    src: env.j2
    dest: "{{ templar_path }}/.env"
    mode: "0644"
  tags: templar

- name: Configure PM2 ecosystem file
  template:
    src: ecosystem.config.js.j2
    dest: "{{ templar_path }}/ecosystem.config.js"
    mode: "0644"
  tags: templar

- name: Start validator processes via PM2
  shell: pm2 start ecosystem.config.js --only "TV{{ item }}"
  args:
    chdir: "{{ templar_path }}"
  loop: "{{ range(1, validator_hotkeys|length + 1) | list }}"
  when: validator_hotkeys|length > 0
  tags: templar

- name: Start aggregator processes via PM2
  shell: pm2 start ecosystem.config.js --only "TA{{ item }}"
  args:
    chdir: "{{ templar_path }}"
  loop: "{{ range(1, (aggregator_hotkeys|default([]))|length + 1) | list }}"
  when: (aggregator_hotkeys|default([]))|length > 0
  tags: templar

- name: Start miner processes via PM2
  shell: pm2 start ecosystem.config.js --only "TM{{ item }}"
  args:
    chdir: "{{ templar_path }}"
  loop: "{{ range(1, miner_hotkeys|length + 1) | list }}"
  when: miner_hotkeys|length > 0
  tags: templar
