---

- name: Create templar directory on remote host
  file:
    path: "{{ ansible_env.HOME }}/templar"
    state: directory
    mode: '0755'
  tags: templar

- name: Synchronize local Templar code to remote host
  synchronize:
    src: "{{ playbook_dir }}/../../"
    dest: "{{ ansible_env.HOME }}/templar"
    rsync_opts:
      - "--exclude=.venv"
      - "--exclude=__pycache__"
      - "--exclude=*.pyc"
    delete: yes
  tags: templar

- name: Debug templar_path and check structure
  shell: |
    echo "templar_path: {{ templar_path }}"
    ls -la {{ templar_path }}/
    ls -la {{ templar_path }}/src/ || echo "src directory not found"
  register: debug_output
  tags: templar

- name: Show debug output
  debug:
    var: debug_output.stdout_lines
  tags: templar

- name: Check if src/tplr/__init__.py exists
  stat:
    path: "{{ templar_path }}/src/tplr/__init__.py"
  register: init_py_stat
  tags: templar

- name: Update version in __init__.py for remote deployment
  replace:
    path: "{{ templar_path }}/src/tplr/__init__.py"
    regexp: '^__version__ = "[^"]+"'
    replace: '__version__ = "{{ templar_version | default("0.2.52dev") }}"'
  when: init_py_stat.stat.exists
  tags: templar
