[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tplr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bittensor==8.5.1",
    "bt-decode==0.4.0",
    "torch",
    "boto3",
    "einops",
    "aiofiles",
    "aioboto3",
    "aiobotocore",
    "transformers",
    "pip",
    "wandb",
    "python-dotenv",
    "zstandard",
    "Flask==2.2.2",
    "Flask-SQLAlchemy==2.5.1",
    "Flask-Migrate==3.1.0",
    "asyncio==3.4.3",
    "werkzeug==2.2.3",
    "matplotlib",
    "seaborn"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
