---
env_vars:
  WANDB_API_KEY: ""
  INFLUXDB_TOKEN: ""  # Optional, falls back to default if not provided
  R2_ACCOUNT_ID: ""
  R2_GRADIENTS_ACCOUNT_ID: ""
  R2_GRADIENTS_BUCKET_NAME: ""
  R2_READ_ACCESS_KEY_ID: ""
  R2_READ_SECRET_ACCESS_KEY: ""
  R2_GRADIENTS_READ_ACCESS_KEY_ID: ""
  R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ""
  R2_WRITE_ACCESS_KEY_ID: ""
  R2_WRITE_SECRET_ACCESS_KEY: ""
  R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ""
  R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ""
  R2_DATASET_WRITE_ACCESS_KEY_ID: ""
  R2_DATASET_WRITE_SECRET_ACCESS_KEY: ""
  R2_DATASET_ACCOUNT_ID: "dd08f378791881bf6bbb7f161c78a220"
  R2_DATASET_BUCKET_NAME: "edu-dataset"
  R2_DATASET_READ_ACCESS_KEY_ID: "7cadbe19f880785e46898b558ef70ce8"
  R2_DATASET_READ_SECRET_ACCESS_KEY: "9787434d676b05dce69cc4e76c6af74d795b606feafd031944444780d5f72272"
  WALLET_NAME: ""
  NETWORK: "finney"
  NETUID: "3"
  DEBUG: "false"
  GITHUB_USER: ""
  # CUDA_DEVICE: ""
  # WALLET_HOTKEY: ""

# Whether to use Systemd or not
use_systemd: false

# Miner cli parameters
actual_batch_size: 5
netuid: "3"
subtensor_network: "finney"
wallet_name: ""

# device: "cuda"
# wallet_hotkey: ""
cuda_devices: ["cuda:0"]
wallet_hotkeys: ["miner_0"]

apt_packages:
  - less
  - vim
  - nvtop
  - htop
  - rsync
  - git
  - python3-pip
  - python3-venv
  - zsh

additional_apt_packages: []

# Global pip packages to install (via pip3)
essential_pip_packages:
  - uv

additional_pip_packages: []

# Pip packages to install in .venv with `uv pip`.
additional_uv_pip_packages: []
