---
- name: Provision Templar instances per GPU
  hosts: all
  become: true
  vars_files:
    - group_vars/all/vault.yml
  vars:
    workspace_dir: "{{ ansible_env.HOME }}/workspace"
  pre_tasks:
    - name: Verify cuda_devices and wallet_hotkeys arrays match in length
      assert:
        that: cuda_devices|length == wallet_hotkeys|length
        fail_msg: "cuda_devices and wallet_hotkeys must have the same number of items"
  tasks:
    - name: Include templar role for each GPU instance
      include_role:
        name: templar
      vars:
        device: "{{ cuda_devices[idx] }}"
        wallet_hotkey: "{{ wallet_hotkeys[idx] }}"
        templar_dir: "{{ workspace_dir }}/templar-{{ cuda_devices[idx] | regex_replace('^cuda:?','') }}"
        miner_index: idx
      loop_control:
        index_var: idx
      loop: "{{ range(0, cuda_devices|length)|list }}"
